prompt PL/SQL Developer import file
prompt Created on sexta-feira, 28 de setembro de 2018 by roterdam.junior
set feedback off
set define off
prompt Creating TB_PLANO_EXECUCAO...
create table TB_PLANO_EXECUCAO
(
  NOME_EMPRESA      VARCHAR2(200),
  DEPOSITO_MENSAL   NUMBER(10,2) not null,
  ID_PLANO_EXECUCAO NUMBER not null,
  CNPJ              VARCHAR2(30),
  CONTA_CORRENTE    VARCHAR2(20),
  DT_DEFERIMENTO    DATE
)
;
alter table TB_PLANO_EXECUCAO
  add constraint PLANO_PK primary key (ID_PLANO_EXECUCAO);

prompt Disabling triggers for TB_PLANO_EXECUCAO...
alter table TB_PLANO_EXECUCAO disable all triggers;
prompt Deleting TB_PLANO_EXECUCAO...
delete from TB_PLANO_EXECUCAO;
commit;
prompt Loading TB_PLANO_EXECUCAO...
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('Santa Casa Misericórdia', 300000, 1, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('CEDAE', 400000, 2, null, null, to_date('22-02-2013', 'dd-mm-yyyy'));
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('Botafogo FR', 500000, 3, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('Consórcio Santa Cruz', 0, 4, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('ÁGUAS SANT’ANNA', 0, 5, null, null, to_date('26-11-2016', 'dd-mm-yyyy'));
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('APAE: ', 0, 6, null, null, to_date('10-09-2016', 'dd-mm-yyyy'));
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('ASSOCIAÇÃO FACULDADES CATÓLICAS PETROPOLITANAS', 0, 7, null, null, to_date('18-11-2014', 'dd-mm-yyyy'));
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('AUTO COMERCIAL BARRA MANSA / VIAÇÃO FALCÃO / PORTO REAL', 0, 9, null, null, to_date('03-09-2016', 'dd-mm-yyyy'));
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('ATRIO RIO', 0, 8, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('CÂNDIDO MENDES (ASSOCIAÇÃO SOCIEDADE BRASILEIRA DE INSTRUÇÃO): ', 0, 10, null, null, to_date('13-04-2018', 'dd-mm-yyyy'));
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('CRUZ VERMELHA', 0, 11, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('FEDERAÇÃO DAS APAEs: ', 0, 12, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('FLUMINENSE', 0, 13, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('GRUPO EBX (AVX TÁXI AÉREO LTDA, ', 0, 14, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('HOSPITAL EVANGÉLICO: ', 0, 15, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('LOCANTY / IMPORT SERVICE / INFORNOVA', 0, 16, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('MPE ENGENHARIA E SERVIÇOS S/A, AGROMON S/A', 0, 17, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('RÁDIO TUPI ', 0, 18, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('REAL AUTO ONIBUS E PREMIUM ', 0, 19, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('REGINAVES', 0, 20, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('SANTA ÚRSULA', 0, 21, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('SEREDE / TELEMOM', 0, 22, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('SESNI – ASSOCIAÇÃO DE ENSINO SUPERIOR DE NOVA IGUAÇU', 0, 23, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('SOCIEDADE ITALIANA', 0, 24, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('TB TRANSPORTES BLANCO / UNIRIO TRANSPORTES: ', 0, 25, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('TRANSPORTES AMIGOS UNIDOS: ', 0, 26, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('TRANSPORTES PARANAPUAN', 0, 27, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('VASCO DA GAMA', 0, 28, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('VIAÇÃO VG EIRELI / CITY RIO ROTAS TURÍSTICAS', 0, 29, null, null, null);
insert into TB_PLANO_EXECUCAO (NOME_EMPRESA, DEPOSITO_MENSAL, ID_PLANO_EXECUCAO, CNPJ, CONTA_CORRENTE, DT_DEFERIMENTO)
values ('VOLTA REDONDA', 0, 30, null, null, null);
commit;
prompt 30 records loaded
prompt Enabling triggers for TB_PLANO_EXECUCAO...
alter table TB_PLANO_EXECUCAO enable all triggers;
set feedback on
set define on
prompt Done.
